version: "2"

services:
  selenium:
    image: selenium/standalone-chrome:3.11.0
    volumes:
      - /dev/shm:/dev/shm
  crystal:
    image: crystallang/crystal:1.6.0-alpine
    command: crystal --version
    environment:
      SELENIUM_SERVER: selenium
      SELENIUM_PORT: 4444
    volumes:
      - .:/mnt
    working_dir: /mnt
    depends_on:
      - selenium
